config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#index"

  get "about" => "top#about", as: "about"
  get "bad_request" => "top#bad_request"
  get "forbidden" => "top#forbidden"
  get "internal_server_error" => "top#internal_server_error"
  
  resources :plans, only: [:index, :show] do
    get "search", on: :collection
  end
  resources :mypages do
    get "index", on: :collection
  end

  resources :members, only: [:index, :new, :create]
  resource :session, only: [:create, :destroy]
  resources :reservations, only: [:new, :create, :show]

  namespace :admin do
    root to: "top#index"
    resources :plans
    resources :members, only: [:index]
    resources :dinners, except: [:edit, :update]
    resources :reservations, except: [:new, :create]
    resource :session, only: [:create, :destroy]
    resources :rooms, only: [:index]
  end


end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::Base
  before_action :admin_login_required
  def index
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/views/admin/top/index.html.erb
<% @page_title = "Admin page" %>
<h1><%= @page_title %>
<table>
    <tr>
        <td><%= link_to "User Accounts", admin_members_path %></td>
    </tr>
    <tr>
        <td><%= link_to "Reservations", admin_reservations_path %></td>
    </tr>
    <tr>
        <td><%= link_to "Plans", admin_plans_path %></td>
    </tr>
    <tr>
        <td><%= link_to "Dinner", admin_dinners_path %></td>
    </tr>
    <tr>
        <td><%= link_to "Rooms", admin_rooms_path %></td>
    </tr>
</table>