config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#index"

  get "about" => "top#about", as: "about"
  get "bad_request" => "top#bad_request"
  get "forbidden" => "top#forbidden"
  get "internal_server_error" => "top#internal_server_error"
  
  resources :plans, only: [:index, :show] do
    get "search", on: :collection
  end
  resources :mypages do
    get "index", on: :collection
  end

  resources :members, only: [:index, :new, :create]
  resource :session, only: [:create, :destroy]
  resources :reservations, only: [:new, :create, :show]

  namespace :admin do
    root to: "top#index"
    resources :plans
    resources :members, only: [:index]
    resources :dinners, except: [:edit, :update]
    resources :reservations, except: [:new, :create]
    resource :session, only: [:create, :destroy]
    resources :rooms, only: [:index]
  end


end

app/views/shared/_admin_login.html.erb
<% @page_title = "Admin Login Required" %>
<h1> Admin mode</h1>
<% if flash.alert %> 
<p class = "alert"><%= flash.alert %></p><% end %>
<%= form_tag admin_session_path, id: "admin_login" do %>
    <div>
        <label>User Name</label>
        <input type = "text" name = "user" >
    </div>
    <div>
        <label>Password:</label>
        <input type = "password" name = "password" >
    </div>
    <div>
        <input type = "submit" value = "login">
    </div>
<% end %>

app/views/shared/_check_params.html.erb
<%= params.inspect %>
<%= params[:key].inspect %>

app/views/shared/_dinner_form.html.erb
<table class = "attr">
    <tr>
        <th><%= form.label :name %></th>
        <td><%= form.text_field :name %></td>
    </tr>
    <tr>
        <th><%= form.label :dish %></th>
        <td><%= form.text_field :dish %></td>
    </tr>
    <tr>
        <th><%= form.label :cost%></th>
        <td><%= form.number_field :cost%></td>
    </tr>
    <tr>
        <th><%= form.label :kcal%></th>
        <td><%= form.number_field :kcal%></td>
    </tr>
</table>

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
    <div id = "errors">
        <h3>Notice</h3>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="center">
	<p id="footer">住所 : 259-0300 神奈川県 湯河原町 XXXX-OOOO</p>
	<p id="footer">電話番号 : 0465-0000-0000</p>
	<p id="footer">photos by pakutaso.com</p>
	<%= render "shared/check_params" %>
	<% if current_member %>
		<%= current_member.name + "さん" %>
		<%= menu_link_to "Logout", :session, method: :delete, data: { confirm: "Are you sure logout? "} %>
	<% end %>

	<% if session[:member_id] == "admin" %>
		<%= "admin mode" %>
		<%= menu_link_to "Logout", admin_session_path, method: :delete, data: { confirm: "Are you sure logout? "}%>
	<% end %>
</div>

app/views/shared/_header.html.erb
<p id="kinsen">琴線</p>

app/views/shared/_login_form.html.erb
<% @page_title = "Login Required" %>
<% if flash.alert %> 
<p class = "alert"><%= flash.alert %></p><% end %>
<%= form_tag :session, id: "login_form" do %>
    <div>
        <label>Email:</label>
        <input type = "email" name = "email" >
    </div>
    <div>
        <label>Password:</label>
        <input type = "password" name = "password" >
    </div>
    <div>
        <input type = "submit" value = "login">
    </div>
<% end %>

app/views/shared/_nav.html.erb
<ul id="nav">
	<li><%= link_to "TOP", root_path %></li>
	<li><%= link_to "Plans", plans_path %></li>
	<li><%= link_to "My Page", mypages_path %></li>
	<li><%= link_to "About", "/#" %></li>
</ul>

app/views/shared/_plan_form.html.erb
<table class = "attr">
    <tr>
        <th><%= form.label :name %></th>
        <td><%= form.text_field :name %></td>
    </tr>
    <tr>
        <th><%= form.label :type_id %></th>
        <td><%= form.number_field :type_id %></td>
    </tr>
    <tr>
        <th><%= form.label :dinner_id%></th>
        <td><%= form.number_field :dinner_id%></td>
    </tr>
    <tr>
        <th><%= form.label :plan_start%></th>
        <td><%= form.date_select :plan_start, start_year: Time.current.year, use_month_numbers: true %></td>
    </tr>
    <tr>
        <th><%= form.label :plan_end %></th>
        <td><%= form.date_select :plan_end, start_year: Time.current.year, use_month_numbers: true %></td>
    </tr>
    <tr>
        <th><%= form.label :guest_max %></th>
        <td><%= form.number_field :guest_max %></td>
    </tr>
    <tr>
        <th><%= form.label :guest_min %></th>
        <td><%= form.number_field :guest_min %></td>
    </tr>
</table>