config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#index"

  get "about" => "top#about", as: "about"
  get "bad_request" => "top#bad_request"
  get "forbidden" => "top#forbidden"
  get "internal_server_error" => "top#internal_server_error"
  
  resources :plans, only: [:index, :show] do
    get "search", on: :collection
  end
  resources :mypages do
    get "index", on: :collection
  end

  resources :members, only: [:index, :new, :create]
  resource :session, only: [:create, :destroy]
  resources :reservations, only: [:new, :create, :show]

  namespace :admin do
    root to: "top#index"
    resources :plans
    resources :members, only: [:index]
    resources :dinners, except: [:edit, :update]
    resources :reservations, except: [:new, :create]
    resource :session, only: [:create, :destroy]
    resources :rooms, only: [:index]
  end


end

app/models/dinner.rb
class Dinner < ApplicationRecord
    has_many :plans
end

app/controllers/admin/dinners_controller.rb
class Admin::DinnersController < ApplicationController
  def index
    @dinners = Dinner.all
  end

  def show
    @dinner = Dinner.find(params[:id])
  end

  def new
    @dinner = Dinner.new
  end

  def create
    @dinner = Dinner.new(params[:dinner])
    if @dinner.save
      redirect_to admin_dinners_path, notice: "Created"
    else
      render "new"
    end
  end

  def destroy
    @dinner = Dinner.find(params[:id])
    @dinner.destroy
    redirect_to admin_dinners_path, notice: "Deleted"
  end
end

app/views/admin/dinners/create.html.erb
<h1>Admin::Dinners#create</h1>
<p>Find me in app/views/admin/dinners/create.html.erb</p>

app/views/admin/dinners/destroy.html.erb
<h1>Admin::Dinners#destroy</h1>
<p>Find me in app/views/admin/dinners/destroy.html.erb</p>

app/views/admin/dinners/index.html.erb
<% @page_title = "admin: Dinner list"%>
<%= link_to "create dinner", new_admin_dinner_path %>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Dish</th>
            <td>manegement</th>
        </tr>
    </thead>
<% @dinners.each do |dinner| %>
<tr>
    <td><%= dinner.name %></td>
    <td><%= dinner.dish %></td>
    <td align="center">
        <%=link_to "detail", [:admin, dinner]%>
        <%=link_to "delete", [:admin, dinner], method: :delete ,data: { confirm: "Are you sure delete this plan?"} %>
    </td>
</tr>
<% end %>
</table>


    

app/views/admin/dinners/new.html.erb
<% @page_title = "Admin: Create new dinner" %>
<%= form_for [:admin, @dinner] do |form|%>
    <%= render "shared/dinner_form", form: form %>
    <div><%= form.submit %></div>
<% end %>

app/views/admin/dinners/show.html.erb
<% @page_title = "admin:" +@dinner.name%>
<table>
    <tr>
        <th>Name</th>
        <td><%=@dinner.name %></td>
    </tr>
    <tr>
        <th>Dish</th>
        <td><%=@dinner.dish %></td>
    </tr>
    <tr>
        <th>cost</th>
        <td><%=@dinner.cost %></td>
    </tr>
    <tr>
        <th>kcal</th>
        <td><%=@dinner.kcal %></td>
    </tr>
    <tr>
        <th>manegemant</th>
        <td><%= link_to "delete",[:admin, @dinner], method: :delete, data: {confirm: "Are you sure delete this plan?"}%>
    </tr>
     

    
    
</table>