config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#index"

  get "about" => "top#about", as: "about"
  get "bad_request" => "top#bad_request"
  get "forbidden" => "top#forbidden"
  get "internal_server_error" => "top#internal_server_error"
  
  resources :plans, only: [:index, :show] do
    get "search", on: :collection
  end
  resources :mypages do
    get "index", on: :collection
  end

  resources :members, only: [:index, :new, :create]
  resource :session, only: [:create, :destroy]
  resources :reservations, only: [:new, :create, :show]

  namespace :admin do
    root to: "top#index"
    resources :plans
    resources :members, only: [:index]
    resources :dinners, except: [:edit, :update]
    resources :reservations, except: [:new, :create]
    resource :session, only: [:create, :destroy]
    resources :rooms, only: [:index]
  end


end

app/models/plan.rb
class Plan < ApplicationRecord
    has_many :assignments, dependent: :destroy
    has_many :types, through: :assignments
    
    has_many :reservations

    belongs_to :dinner

    
    class << self
        def search(*query)
            guest_num = query[0].to_f
            required_rooms = (guest_num / 4.to_f).ceil #この予約で必要な部屋数
            date_start = query[1]
            2.upto(3) do |i|
                date_start = date_start + "-" 
                date_start = date_start + query[i]
            end

            date_end = query[4]
            5.upto(6) do |i|
                date_end = date_end + "-"
                date_end = date_end + query[i]
            end
            date_start = Date.parse(date_start)
            date_end = Date.parse(date_end)
            plans = Plan.where("plan_start <= ? and plan_end >= ?", date_start, date_end)
            
            #Plan.idな総部屋数
            room_count = Array.new(plans.count + 1,0)
            plans.each do |plan|
                Room.all.each do |room|
                    if plan.types.ids.sort == room.types.ids.sort
                        room_count[plan.id] = room_count[plan.id] + 1 
                    end
                end
            end
            plans.each do |plan|
                p plan.types.ids
            end
            p "------check_room_count---------------------"
            p room_count
            #---------------------------------------------------
            
            #reserved = Reservation.where("date_start <= ? AND ? >= date_end or date_start <= ? AND ? >= date_end", date_start, date_start, date_end, date_end  )
            reserved = Reservation.where("date_start BETWEEN ? AND ? or date_end BETWEEN ? AND ?", date_start, date_end, date_start, date_end)
            reserved.each do |reservation|
                p "----reserved.query.by ? <= date_start and date_end <= ? --------"
                p reservation
            end   
            
            reserved_room_count = 0
            # reserved.each do |reservation|
            #     reserved_room_count = (reservation.guest_count.to_f / 4.0).ceil
            #     room_count[reservation.plan_id] = room_count[reservation.plan_id] - reserved_room_count
            # end
            

            plans.each do |plan|
                reserved.each do |reservation|
                    pre_reservation_types = reservation.type_id.split(",")
                    reservation_types = []
                    for n in pre_reservation_types
                        reservation_types.push(n.to_i)
                    end
                    if plan.types.ids == reservation_types
                        p "Found Reserved Room Query By types"
                        p reservation_types
                        reserved_room_count = (reservation.guest_count.to_f / 4.0).ceil #type[1,2,3]は 1部屋利用されている。
                        room_count[plan.id] = room_count[plan.id] - reserved_room_count
                
                    end
                    p "--------reservation_types_pushed-----------"
                    p reservation_types
                end
            end

            p "---check_room_count_after_edit----------------------------"
            p room_count
            
            available_plan = Array.new(plans.count + 1, false)
            available_plan_id = Array.new(plans.count + 1, nil)
            1.upto(room_count.length - 1) do |idx|
                if room_count[idx] >= required_rooms
                    available_plan[idx] = true
                end 
                if available_plan[idx] == true
                    available_plan_id[idx] = idx 
                end
            end

            p "------check_available_plan--------------------------------"
            p available_plan
            p "------check_available_plan_id--------------------------------"
            available_plan_id.delete(nil)
            p available_plan_id
            plans =  Plan.find(available_plan_id)
            plans
        end
    end
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(params[:plan])
    if @plan.save
      redirect_to admin_plans_path, notice: "Created"
    else
      render "new"
    end
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    @plan.assign_attributes(params[:plan])
    if @plan.save
      redirect_to admin_plans_path, notice: "Updated"
    else
      render "edit"
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to admin_plans_path, notice: "Deleted"
  end

  def show
    @plan = Plan.find(params[:id])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
  end

  def search
    @plans = Plan.search(params[:guest_num], params["date_start(1i)"],params["date_start(2i)"], params["date_start(3i)"],
             params["date_end(1i)"],params["date_end(2i)"],params["date_end(3i)"])
    render "index"
  end

  def show
    @plan = Plan.find(params[:id])
  end
end

app/views/plans/index.html.erb
<% @page_title = "Search plan" %>
<h1><%= @page_title %></h1>
<%
=begin%>
 <%= form_tag :search_plans, method: :get, class: "search" do %>
    <%= text_field_tag "q", params[:q] %>
    <%Type.all.each do |type| %>
        <%= check_box_tag "#{type.name}" %><%=type.name%>
    <% end %>
    <%= submit_tag "search" %>
<% end %> 
<%
=end
%>

<%= form_with url: search_plans_path, method: :get, local: true do |form| %>
     <% guestop = ["1",1],["2",2],["3",3],["4",4],["5",5],["6",6] %>
    宿泊人数：<%= select_tag :guest_num, options_for_select(guestop,1)%>
    <%= form.date_select :date_start, {start_year: Time.current.year, end_year: Time.current.year + 1, use_month_numbers: true}%>
    ～
    <%= form.date_select :date_end, {start_year: Time.current.year, end_year: Time.current.year + 1, use_month_numbers: true}%>
    <%= form.submit "Search" %>
<% end %>

<hr>



<% if @plans != nil %>
    <table class="list">
        <% @plans.each do |plan| %>
        <tr>
            <th><%= plan.name %></th>
            <td><%= link_to "Detail", plan %><td>
        </tr>
        <% end %>
    </table>
<% end %>

app/views/plans/search.html.erb
<h1>Plans#search</h1>
<p>Find me in app/views/plans/search.html.erb</p>

app/views/plans/show.html.erb
<% @page_title = @plan.name %>
<h1><%= @plan.name %> 詳細</h1>
	<div class="plan">
		<h2 id="plan">概要</h2>
		<ul>
			<li>お夕食 : <%= @plan.dinner.name %></li>
			<% @plan.types.each do |type| %>
				<li><%= type.name %></li>
			<% end %>
		</ul>
	</div>

	<div class="plan">
		<h2 id="plan">お夕食 <%= @plan.dinner.name %></h2>
		<ul>
			<li><%= safe_join("#{@plan.dinner.dish}".split("\n"),tag(:br)) %></li>
			<li><%= "#{@plan.dinner.kcal} kcal" %></li>

		</ul>

	</div>
    <h3>選べるお部屋</h3>
	<% @plan.types.each do |type| %>
		<div class="plan">
			<p id="plan"><%= type.name %></p>
		</div>	
	<% end %>
<%= link_to "予約画面へ", new_reservation_path(plan_id: @plan.id) %>